version: '{build}'
skip_tags: true
image: Visual Studio 2017
configuration: Release
install:
  - ps: mkdir -Force ".\build\" | Out-Null
  - ps: Invoke-WebRequest "https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.ps1" -OutFile ".\build\installcli.ps1"
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetcli"
  - ps: '& .\build\installcli.ps1 -InstallDir "$env:DOTNET_INSTALL_DIR" -NoPath -Version 1.0.1'
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"
test: off
build_script:
- ps: ./Build.ps1
artifacts:
- path: artifacts/Destructurama.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: Db273rounfdesOqPXjqPrP6jeHGKkI52Rk+FSdnh6X/S6MuCelVFMpVMn67CcZgv
  skip_symbols: true
  on:
    branch: /^(master|dev)$/
